### ISSUE TITLE
The 1.0.7 TTF file is not being applied.

### ISSUE THREAD

**Issue by rascapple** [vasyl91/DisplayMediaTitles#3]
We tested version 1.0.7 in advance by installing it on an AOS Galaxy S21. However, the .ttf file could not be applied on the phone, so we tried installing it on an FYT device, but it still didn’t work. Please check this issue. I am curious if the file needs to be placed in a specific folder or if there is a size limit for .ttf files.

**Comment by vasyl91** [comment]
[This is the font](https://github.com/user-attachments/files/18051919/pacifico.ZIP) that I tested. It can be picked from anywhere. Have you tried different `.ttf` files or only one? Maybe it's the question of the file size. 
![Screenshot_20241208-130749](https://github.com/user-attachments/assets/a442bc2a-2197-4fe6-aa02-dc1ce2d00c3b)

**Comment by rascapple** [comment]
I tried all the ttf files, but it didn’t work. I am Korean, and ttf files
that usually include Korean and English are typically between 4 to 7 MB in
size. Is there a way to increase the supported file size?

2024년 12월 8일 (일) 21:09, Hubert ***@***.***>님이 작성:

**Comment by rascapple** [comment]
I just tried applying files smaller than 1MB, but there was no response.

**Comment by vasyl91** [comment]
Please attach here flies that you tried and I'll see what can be done.

**Comment by rascapple** [comment]
> Please attach here flies that you tried and I'll see what can be done.

It seems I can only upload photos here. I will send it to your email address, so please leave your email.

**Comment by vasyl91** [comment]
vasyl91@gmail.com

**Comment by vasyl91** [comment]
I used both files that you had sent and it works, take a look at the attached screenshots. I'll generate apk again and repost it. Maybe that's the issue. Unfortunately I'm not at home, so I'll be able to do that tomorrow. ![Screenshot_20241208-145237](https://github.com/user-attachments/assets/74d6aa71-e401-47a4-8afe-5dd6a2d4b145)
![Screenshot_20241208-145300](https://github.com/user-attachments/assets/c9b98f48-0b23-4e17-92de-583d797a3ca6)

**Comment by rascapple** [comment]
Thank you for confirming. If you re-upload the APK file tomorrow, I will test it again.

Lastly, I have a suggestion and a request. 

Currently, the system displays both the singer's name and the song title. Would it be possible to add a feature to remove the singer's name? Options like "Hide Singer Name" or "Hide both the song title and the artist's name." would be great.

The reason is that in certain music players, lyrics embedded in the song file as tags can be displayed on the system's top bar. However, when the singer's name, song title, and lyrics are all shown, the space becomes insufficient, causing the lyrics to be heavily truncated. There are many situations where I just want to display the "lyrics," but even editing the "file name" does not seem to apply to FYT-series devices.

If you have time tomorrow, I will record a video explaining it in a way that is easy for the developer to understand and send it via email. Please take a look and review it. Thank you for your feedback today.

**Comment by vasyl91** [comment]
There are two data sets displayed on the status bar - the title and the artist (if it's present in the metadata). Adding feature allowing displaying solely the title will be easy to implement however elegant way to remove unwanted stuff from it is impossible, because it's being displayed as it is.

Removing the artist name from the title metadata is also easy (simple string edition, provided that the artist name is available in the metadata) but the result would certainly look weird, because the title might contain the artist name in various ways i.e "artist - title", "title - artist", "title (by artist ft. XYZ)" etc. Removing artist from the title will leave something like "title (by ft. XYZ)" or  " - title".

**Comment by rascapple** [comment]
Would it be possible to display only the "lyrics" information contained in the metadata of the playback file? Temporarily hiding the artist name and title, and implementing a way to retrieve only the embedded lyrics data in the file, would be difficult, right?

**Comment by vasyl91** [comment]
Sorry, the whole app revolves around the media title and artist name. It will not provide lyrics feature.

**Comment by rascapple** [comment]
Yes, thank you. If it's possible to implement at least a feature to hide the singer's name or song title, I would like to request that.

**Comment by rascapple** [comment]
First of all, thank you for uploading version 1.0.8. The singer name and song title features have also been added right away. They are working well.

However, the .ttf file is still not being applied. I tested with the .ttf file I sent yesterday, but it still doesn't work.

**Comment by vasyl91** [comment]
I've just released 1.0.8 version which allows user to choose whether to display the artist's name or not. 

Code in terms of .ttf files remains the same. Everything works, I tested it both on phone and on FYT7862 (please check the attached screenshot and gallery in README.MD). The only thing I've noticed is that some devices might have problem with 'Storage Access Framework' and need to have some additional app installed (which is provided in the release). 

If you still don't manage to open font file then the issue it's probably not related to the app itself and I won't be much help.

![Screenshot_20241209-164937](https://github.com/user-attachments/assets/e2e23214-2a13-48cc-8f0c-5ad1aa9dab9c)

**Comment by rascapple** [comment]
This is a test done first on the Galaxy S21. My device is FYT7870, and I will test it tomorrow. Thank you.

**Comment by vasyl91** [comment]
I'll have Samsung A55 this week, maybe it's the question of the Samsung device. I'll check that.

**Comment by rascapple** [comment]
In FYT7870, applying the TTF file still does not work. There are two other third-party apps where TTF application works well. Please review this issue again, considering this aspect.

**Comment by rascapple** [comment]
I've tested it again. The conclusion is that it works well. You need to enter the default built-in "Android file app" and select the TTF file for it to apply.
